### ISSUE TITLE
Issue with PyJEM Download from GitHub Repository

### ISSUE THREAD

**Issue by PyJEM** [PyJEM/PyJEM#24]
Issues received individually
The following are the contents of the report.

> I hope this message finds you well. I am writing to inform you about an issue I encountered while attempting to download PyJEM from the GitHub directory.
> Following the guidelines provided, I utilized the Conda command to download the virtual environment. However, upon completing the download and attempting to set up the virtual environment, I encountered an error. The Conda command mentioned in the guide triggered an error message, making it impossible for me to proceed with setting up PyJEM. 
> Additionally, we were unable to locate the PyJEM.zip file mentioned in the guideline. It seems to be missing or not available in the specified location.
> Thank you for your attention to this matter. I look forward to your prompt response.
>

**Comment by dmaekawa** [comment]
Thank you for your inquiry.

Answer about the installation of a virtual environment.
Here, too, we installed the virtual environment according to the manual and confirmed that the error occurred.

Error messages are as follows: 
`CondaValueError: The target prefix is the base prefix. Aborting.`

The commands listed in the manual are incorrect, please execute the following commands.
  `conda env create -f vjem_yml`

**Comment by dmaekawa** [comment]
We have also confirmed that the installation of virtual environment vjem35.yml, vjem37.yml, vjem38.yml has failed.
Please use vjem39 or vjem310 until we fix it.

**Comment by m-koshino** [comment]
Thanks for the instructive information. I have two problems when updating from pyjem38 to the upper.
One is the yml files. For vjem39 and vjem310, it seems that the intel conda channel is no longer available.
I could avoid the discrepancy by removing intel channel and related libraries in the yml files.
Another problem is the PyJEM installer.
I could download the latest PyJEM.zip from Forum. According to https://pyjem.github.io/PyJEM/Appendix/Installer.html, it is described that "※This installer is included in the equipment package purchased." 
We have purchased a new microsope in 2023, coming with an installer DVD, "VEM1342-11 (2021/12/09)". The installer only contains cui -based bat files NOT gui. I tried to modify bat files which does not work so far. Need some help. Best,

**Comment by dmaekawa** [comment]
@m-koshino 

Thank you for contacting us.
We will respond to your two pronblems.


**I. the intel conda channel is no longer available.**

Thank you for sharing this information.We were not aware that the intel channel was not available.Because the published yml refers to the intel channel,I would like to make a change to configure numpy in conda-forge.

If you know how to install numpy-mkl in a conda environment, could you please let me know?


**II. About PyJEM installer (VEM1342-11)**

We apologize for the omission of the installation procedure for VEM1342-11.
The installation procedure is as follows

1. start the command prompt
2. activate the virtual environment
3. mount VEM1342-11 on any drive 4.
4. run media\updater.exe from 3. at 2.
  Arguments
    -l: License file path
    -p: Downloaded PyJEM file

You can install the software by executing the above.

![image](https://github.com/user-attachments/assets/32497421-acd3-4e47-b0b2-c8a4523a0b1b)

best regards.

**Comment by mkoshino** [comment]
> If you know how to install numpy-mkl in a conda environment, could you please let me know?

Although I stick to numpy in conda-forge I could find some information at, 
https://anaconda.org/search?q=numpy-mkl
The given files are 9 years old or more so that I have not tried them yet.

> **II. About PyJEM installer (VEM1342-11)**
> We apologize for the omission of the installation procedure for VEM1342-11. The installation procedure is as follows

I appreciate your help. 
The installer did not work on my on-line environment with 'JEM Administrator' user account as shown in attached file.
[20240814failed_install_PyJEM.txt](https://github.com/user-attachments/files/16606439/20240814failed_install_PyJEM.txt)
"""
Command [pip install --no-deps C:\Users\JEM Administrator\AppData\Roaming\JEOL\PyJEM\PyJEM.zip] was failed.
Traceback (most recent call last):
  File "setup_project.py", line 44, in _command
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command 'pip install --no-deps C:\Users\JEM Administrator\AppData\Roaming\JEOL\PyJEM\PyJEM.zip' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup_project.py", line 155, in main
  File "setup_project.py", line 55, in command
  File "setup_project.py", line 51, in _command
SystemExit: 1
"""
* The installer worked on my off-line environment with non-space user name, though. 
I am not sure what really cases the failure.
Best,

**Comment by dmaekawa** [comment]
@m-koshino 

Sorry for the delay in getting back to you.

Thanks for the advice on how to install.

> I appreciate your help.
> The installer did not work on my on-line environment with 'JEM Administrator' user account as shown in attached file.

I found the problem with the installation error.
The cause seems to be a space in the user name that performs the installation.

We apologize for the inconvenience,
Could you please create a new user on your PC and try the installation again?

best regards.

**Comment by mkoshino** [comment]
Thank you .
I could install the latest PyJEM library on python310 environment with a user account without a space.
 The installer (updater) may need quotes for file path location. 
` pip install --no-deps "C:\Users\JEM Administrator\AppData\Roaming\JEOL\PyJEM\PyJEM.zip"`
Thanks for the instruction.
